version: "3.8"
services:
  taskhive-web-client:
    build: ./
    container_name: taskhive-frontend
    ports:
      - '3000:3000'
    volumes:
      - ../TaskHive-web-app-client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
